# Generated by Django 2.2.3 on 2019-07-17 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('gender', models.BooleanField(null=True)),
                ('emailVerified', models.BooleanField(null=True)),
                ('status', models.TextField(null=True)),
                ('documentNumber', models.TextField(null=True)),
                ('documentNumberType', models.TextField(null=True)),
                ('photoProfile', models.TextField(null=True)),
                ('photoCover', models.TextField(null=True)),
                ('birthday', models.DateField(null=True)),
                ('typeUser', models.TextField(null=True)),
                ('blood', models.TextField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('createdAt', models.DateField(null=True)),
                ('createdBy', models.IntegerField(null=True)),
                ('updatedAt', models.DateField(null=True)),
                ('updatedBy', models.IntegerField(null=True)),
                ('mobile', models.TextField(null=True)),
                ('mobileVerified', models.BooleanField(null=True)),
                ('referralCode', models.TextField(null=True)),
                ('isVirtual', models.BooleanField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
